<div class="timer">
               Таймер:
               <div class="minute">
               <div class="move" id = "hour">
                 <span>00</span>
                 <span>01</span>
                 <span>02</span>
                 <span>03</span>
                 <span>04</span>
                 <span>05</span>
                 <span>06</span>
                 <span>07</span>
                 <span>08</span>
                 <span>09</span>
                 <span>10</span>
                 <span>11</span>
               </div>
               </div>
               <div class="minute">
               <div class="move" id = "minute">
                 <span>00</span>
                 <span>01</span>
                 <span>02</span>
                 <span>03</span>
                 <span>04</span>
                 <span>05</span>
                 <span>06</span>
                 <span>07</span>
                 <span>08</span>
                 <span>09</span>
                 <span>10</span>
                 <span>11</span>
                 <span>12</span>
                 <span>13</span>
                 <span>14</span>
                 <span>15</span>
                 <span>16</span>
                 <span>17</span>
                 <span>18</span>
                 <span>19</span>
                 <span>20</span>
                 <span>21</span>
                 <span>22</span>
                 <span>23</span>
                 <span>24</span>
                 <span>25</span>
                 <span>26</span>
                 <span>27</span>
                 <span>28</span>
                 <span>29</span>
                 <span>30</span>
                 <span>31</span>
                 <span>32</span>
                 <span>33</span>
                 <span>34</span>
                 <span>35</span>
                 <span>36</span>
                 <span>37</span>
                 <span>38</span>
                 <span>39</span>
                 <span>40</span>
                 <span>41</span>
                 <span>42</span>
                 <span>43</span>
                 <span>44</span>
                 <span>45</span>
                 <span>46</span>
                 <span>47</span>
                 <span>48</span>
                 <span>49</span>
                 <span>50</span>
                 <span>51</span>
                 <span>52</span>
                 <span>53</span>
                 <span>54</span>
                 <span>55</span>
                 <span>56</span>
                 <span>57</span>
                 <span>58</span>
                 <span>59</span>
               </div>
               </div>
               <div class="minute">
               <div class="move" id = "secound">
                 <span>00</span>
                 <span>01</span>
                 <span>02</span>
                 <span>03</span>
                 <span>04</span>
                 <span>05</span>
                 <span>06</span>
                 <span>07</span>
                 <span>08</span>
                 <span>09</span>
                 <span>10</span>
                 <span>11</span>
                 <span>12</span>
                 <span>13</span>
                 <span>14</span>
                 <span>15</span>
                 <span>16</span>
                 <span>17</span>
                 <span>18</span>
                 <span>19</span>
                 <span>20</span>
                 <span>21</span>
                 <span>22</span>
                 <span>23</span>
                 <span>24</span>
                 <span>25</span>
                 <span>26</span>
                 <span>27</span>
                 <span>28</span>
                 <span>29</span>
                 <span>30</span>
                 <span>31</span>
                 <span>32</span>
                 <span>33</span>
                 <span>34</span>
                 <span>35</span>
                 <span>36</span>
                 <span>37</span>
                 <span>38</span>
                 <span>39</span>
                 <span>40</span>
                 <span>41</span>
                 <span>42</span>
                 <span>43</span>
                 <span>44</span>
                 <span>45</span>
                 <span>46</span>
                 <span>47</span>
                 <span>48</span>
                 <span>49</span>
                 <span>50</span>
                 <span>51</span>
                 <span>52</span>
                 <span>53</span>
                 <span>54</span>
                 <span>55</span>
                 <span>56</span>
                 <span>57</span>
                 <span>58</span>
                 <span>59</span>
               </div>
               </div>
          </div>
